language: rust
sudo: required
dist: trusty
addons:
    apt:
        packages:
            - libssl-dev
cache: cargo
rust:
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
before_script:
- cargo install --git https://github.com/xd009642/tarpaulin.git --branch develop cargo-tarpaulin
script:
- cargo clean
- cargo build
- cargo test

after_success: |
  if [[ "$TRAVIS_RUST_VERSION" == stable ]]; then
    cargo tarpaulin --exclude-files src/information_element.rs --ciserver travis-ci --coveralls $TRAVIS_JOB_ID
  fi
