[package]
name = "libipfix"
version = "0.1.0"
authors = ["Julius Rakow <julius@familie-rakow.de>"]

[dependencies]
env_logger = "0.5"
log = "0.4"
nom = "4.0.0-beta1"
serde = "1"
serde_json = "1"

[[bin]]
name = "collector"
path = "src/bin/collector.rs"
